[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NETLIFY_DATABASE_URL = "postgresql://neondb_owner:npg_Oh2BHmCe3Dil@ep-wild-pond-a5cciso6-pooler.us-east-2.aws.neon.tech/neondb?sslmode=require"
  NETLIFY_DATABASE_URL_UNPOOLED = "postgresql://neondb_owner:npg_Oh2BHmCe3Dil@ep-wild-pond-a5cciso6.us-east-2.aws.neon.tech/neondb?sslmode=require"