[build]
  command = "npm run build"
  publish = "dist"

  [build.environment]
    VITE_API_URL = "https://alerion.netlify.app/"
    NODE_VERSION = "20"
    VITE_SUPABASE_URL = "https://uygpgwfruiqqofyltvuy.supabase.co"
    VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5Z3Bnd2ZydWlxcW9meWx0dnV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NTkxMTMsImV4cCI6MjA2NTMzNTExM30.US-P1KFLeuJestoaFtqio-kjjP8AaQ5EXiOdcAcfSxU"
  VITE_REDIS_URL = "redis://default:jsMU2rG7qIKR8KJTOyi3SDClPnRzvmE@redis-14221.c270.us-east-1-3.ec2.redns.redis-cloud.com:14221"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
